version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: PersonalFinanceManager.API/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:8000
      - ConnectionStrings__DefaultConnection=${API_DB_CONNECTION_STRING}
    depends_on:
      - db
    mem_limit: 300m
    networks:
      - pfm-network

  web:
    build:
      context: .
      dockerfile: PersonalFinanceManager.WebHost/Dockerfile
    ports:
      - "7204:7204"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ConnectionStrings__DefaultConnection=${WEB_DB_CONNECTION_STRING}
      - ASPNETCORE_URLS=https://+:7204
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${KESTREL_CERT_PASSWORD}
    depends_on:
      - api
      - db
    mem_limit: 400m
    volumes:
      - ./certs:/app/certs:ro
    networks:
      - pfm-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_SA_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "11433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - pfm-network

networks:
  pfm-network:
    driver: bridge

volumes:
  mssql-data: