name: CD for FinSnap
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH
        uses: webfactory/ssh-agent@v3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to VPS
        env:
          API_DB_CONNECTION_STRING: ${{ secrets.API_DB_CONNECTION_STRING }}
          WEB_DB_CONNECTION_STRING: ${{ secrets.WEB_DB_CONNECTION_STRING }}
          DB_SA_PASSWORD: ${{ secrets.DB_SA_PASSWORD }}
        run: |
          ssh root@103.72.96.116 << 'EOF'
            cd ~/finsnap/PersonalFinanceManager
            git pull origin main
            echo "API_DB_CONNECTION_STRING=$API_DB_CONNECTION_STRING" > .env
            echo "WEB_DB_CONNECTION_STRING=$WEB_DB_CONNECTION_STRING" >> .env
            echo "DB_SA_PASSWORD=$DB_SA_PASSWORD" >> .env
            docker-compose down
            docker-compose up -d --build
            dotnet tool install --global dotnet-ef
            export PATH="$PATH:/root/.dotnet/tools"
            cd PersonalFinanceManager.Infrastructure
            dotnet ef database update
          EOF