name: CI-CD for FinSnap
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
      - name: Restore dependencies
        run: dotnet restore PersonalFinanceManager.sln
      - name: Build API
        run: dotnet build PersonalFinanceManager.API/PersonalFinanceManager.API.csproj --configuration Release --no-restore
      - name: Build WebHost
        run: dotnet build PersonalFinanceManager.WebHost/PersonalFinanceManager.WebHost.csproj --configuration Release --no-restore
      - name: Publish API
        run: dotnet publish PersonalFinanceManager.API/PersonalFinanceManager.API.csproj --configuration Release --no-build --output ./PersonalFinanceManager.API/bin/Release/net8.0/publish
      - name: Publish WebHost
        run: dotnet publish PersonalFinanceManager.WebHost/PersonalFinanceManager.WebHost.csproj --configuration Release --no-build --output ./PersonalFinanceManager.WebHost/bin/Release/net8.0/publish
      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 24700 -H 103.72.96.116 >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: Deploy to VPS
        env:
          API_DB_CONNECTION_STRING: ${{ secrets.API_DB_CONNECTION_STRING }}
          WEB_DB_CONNECTION_STRING: ${{ secrets.WEB_DB_CONNECTION_STRING }}
          DB_SA_PASSWORD: ${{ secrets.DB_SA_PASSWORD }}
          KESTREL_CERT_PASSWORD: ${{ secrets.KESTREL_CERT_PASSWORD }}
        run: |
          ssh -T -p 24700 root@103.72.96.116 << 'EOF'
            cd ~/finsnap/PersonalFinanceManager
            git pull origin main
            echo "API_DB_CONNECTION_STRING=$API_DB_CONNECTION_STRING" > .env
            echo "WEB_DB_CONNECTION_STRING=$WEB_DB_CONNECTION_STRING" >> .env
            echo "DB_SA_PASSWORD=$DB_SA_PASSWORD" >> .env
            docker-compose down
            docker-compose up -d --build
            dotnet tool install --global dotnet-ef
            export PATH="$PATH:/root/.dotnet/tools"
            cd PersonalFinanceManager.API
            dotnet ef database update
          EOF